#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("App3.Resource", IsApplication=true)]

namespace App3
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int monoandroidsplash = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060001
			public const int button1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int button2 = 2131099650;
			
			// aapt resource value: 0x7f06000f
			public const int button25 = 2131099663;
			
			// aapt resource value: 0x7f060003
			public const int button3 = 2131099651;
			
			// aapt resource value: 0x7f060014
			public const int button35 = 2131099668;
			
			// aapt resource value: 0x7f060004
			public const int button4 = 2131099652;
			
			// aapt resource value: 0x7f06000a
			public const int button5 = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int editText1 = 2131099653;
			
			// aapt resource value: 0x7f06000e
			public const int editText2 = 2131099662;
			
			// aapt resource value: 0x7f060007
			public const int radioButton1 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int radioButton2 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int radioButton3 = 2131099657;
			
			// aapt resource value: 0x7f060011
			public const int radioButton31 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int radioButton32 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int radioButton33 = 2131099667;
			
			// aapt resource value: 0x7f06000c
			public const int radioGroup1 = 2131099660;
			
			// aapt resource value: 0x7f060006
			public const int toggleButton1 = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int toggleButton21 = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int toggleButton31 = 2131099664;
			
			// aapt resource value: 0x7f060000
			public const int toolbar1 = 2131099648;
			
			// aapt resource value: 0x7f06000d
			public const int toolbar2 = 2131099661;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Switch1 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Switch2 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Switch3 = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
